default_platform(:ios)

platform :ios do

  desc 'Run unit tests'
  lane :tests do
  	run_tests(
  		scheme: "WeatherAppTests",
  		clean: true,
  		devices: ['iPhone 11'],
  		skip_build: false,
        build_for_testing: true)
  end

  desc 'Lint project files'
  lane :lint do
  	swiftlint(
  		mode: :lint,
  		raise_if_swiftlint_error: true,
  		ignore_exit_status: true)
  end
end