default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc 'Run_unit_tests'
  lane :tests do
  	run_tests(
  		scheme: "WeatherAppTests",
  		clean: true,
  		devices: ['iPhone 11'],
  		skip_build: false,
        build_for_testing: true)
  end
end