name: Run scanning tool on code

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:  

jobs:
  swiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run swiftlint
      run: bundle exec fastlane lint
      # Running unit tests fails, no simulators available
  # build:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Force xcode 11 
  #       run: sudo xcode-select -switch /Applications/Xcode_11.7.app
  #     - name: Run tests
  #       run: xcodebuild test -scheme WeatherAppTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
