name: Run scanning tool on code

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Force xcode 11 
        run: sudo xcode-select -switch /Applications/Xcode_11.1.app
      - name: iOS build setup
        run: xcodebuild build-for-testing -scheme WeatherAppTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
      - name: Test iPhone 11
        run: xcodebuild test-without-building -scheme your-scheme-test -workspace your_project.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
  swiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run swiftlint
      run: bundle exec fastlane lint
