name: Run scanning tool on code

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:  

jobs:
  build:
    swiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run swiftlint
      run: bundle exec fastlane lint
